### PR TITLE
Android/turbomodule vs jsbridge

### PR DESCRIPTION
**Pull request by bozaigao**
Hello, I spent some time to make a demo based on the new architecture of RN, mainly using TurboModule and Fabric. Meanwhile, I compared the performance of J S Bridge, Flutter and native communication. Please accept it!

### CODE REVIEW

**Comment by bozaigao** [comment]
@cortinico hi,the project link:https://github.com/bozaigao/RNNewArchitectureApp/tree/android/turbomodule_vs_jsbridge,
The purpose of this branch is to show some performance differences before and after the new architecture, so that users can have a more dimensional experience of the new architecture. Later I will submit some code in this branch to compare the long list render performance differences between the old and new architectures,So I thought it was necessary to create one

**Comment by bozaigao** [comment]
@cortinico ok,I just want users to know the real performance benefits of the new architecture. I can't create new branches, so which branch can I merge into?

**Comment by cortinico** [comment]
> @cortinico ok,I just want users to know the real performance benefits of the new architecture. I can't create new branches, so which branch can I merge into?

The best would be to have your repo listed in the New Architecture Working Group here:
github.com/reactwg/react-native-new-architecture/

If you don't have access, you can apply with the form in the README

**Comment by bozaigao** [comment]
@cortinico Hello, I have just applied to join the New Architecture Working Group. Please accept my application

**Comment by bozaigao** [comment]
@cortinico ok
331654578252_ pic

**Comment by kelset** [comment]
@bozaigao I might be wrong, but I think that @cortinico meant that you should have your forked repo be its own repo (as in, not merged into another repo) and posted as a comment with a link in this discussion https://github.com/reactwg/react-native-new-architecture/discussions/26

that way folks that want to try it out can see it in that discussion and potentially interact with you in the issue section of your repo. (as it can happen for [RNNewArchitectureApp](https://github.com/react-native-community/RNNewArchitectureApp) and [RNNewArchitectureLibraries](https://github.com/react-native-community/RNNewArchitectureLibraries))

**Comment by cortinico** [comment]
Essentially what @kelset said.

As a rule of thumb @bozaigao, don't merge PRs on Repos you don't own without a specific approval. It's clearly written in the New Architecture working group that this it is a _discussion only_ repository.

We don't want users to update the README as it's too uncoordinated and doesn't allow for further discussion.

Moreover, as we have other projects listed in other discussions, it would have been unfair to have **only** your projects in the front README against the other projects.

**Pull request closed without merging**
